name: Magento Project

on:
  push:
    branches:
    - master
    - staging
  pull_request:
    branches:
    - master
    - staging
    - development
    - feature/*

jobs:
  build:
    uses: AssetMarketingServicesInc/.github/.github/workflows/magento-project.yml@master
    secrets:
      REPO_MAGENTO_COM_USER: ${{ secrets.REPO_MAGENTO_COM_USER }}
      REPO_MAGENTO_COM_PASSWORD: ${{ secrets.REPO_MAGENTO_COM_PASSWORD }}
      SSH: ${{ secrets.SSH }}

  phpcs:
    uses: AssetMarketingServicesInc/.github/.github/workflows/phpcs.yml@master
    needs: build

  phpunit:
    name: PHP Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact-${{ github.sha }}

      - name: Extract Artifact
        run: tar -xf artifact-${{ github.sha }}.tgz && rm artifact-${{ github.sha }}.tgz

      - name: Execute Code Sniffer
        run: /usr/bin/php7.4 ./vendor/bin/phpcs .
