name: Magento Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
    - master
    - feature/*

jobs:
  build:
    uses: AssetMarketingServicesInc/.github/.github/workflows/magento-package.yml@master
    secrets:
      REPO_MAGENTO_COM_USER: ${{ secrets.REPO_MAGENTO_COM_USER }}
      REPO_MAGENTO_COM_PASSWORD: ${{ secrets.REPO_MAGENTO_COM_PASSWORD }}
      SSH: ${{ secrets.SSH }}

  phpcs:
    uses: AssetMarketingServicesInc/.github/.github/workflows/phpcs.yml@master
    needs: build
    
  phpunit:
    uses: AssetMarketingServicesInc/.github/.github/workflows/phpunit.yml@master
    needs: build
